# Generated by Django 2.2.4 on 2019-08-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.CharField(max_length=10)),
                ('e_name', models.CharField(max_length=64)),
                ('e_sal', models.FloatField()),
                ('e_mobile', models.CharField(max_length=13)),
                ('e_city', models.CharField(default='San Jose', max_length=64)),
            ],
        ),
    ]
