# Generated by Django 2.2.4 on 2019-08-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.CharField(max_length=10)),
                ('highest_qualification', models.CharField(max_length=64)),
                ('temporary_address', models.CharField(max_length=128)),
                ('permanent_address', models.CharField(max_length=128)),
            ],
        ),
    ]
